services:

  # admin:
  #   container_name: adminer
  #   image: adminer
  #   restart: always
  #   networks:
  #     - auth
  #     - external
  #   ports:
  #     - 8080:8080

  nginx:
      image: nginx:latest
      container_name: nginx_container
      depends_on:
      - authentication
      - core
      - game
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./backend/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./backend/nginx/ssl:/etc/nginx/ssl:ro
        - media:/media
      networks:
        - internal_network
        - external
      security_opt:
        - no-new-privileges:true

  nginx_front:
      image: nginx:latest
      container_name: nginx_front
      # depends_on:
      ports:
        - "4433:4433"
      volumes:
        - ./frontend/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./frontend/nginx/ssl:/etc/nginx/ssl:ro
        - ./frontend/static_content:/var/www/ft_trascendence:ro
      # networks:
      #   - internal_network
      #   - external

  authentication:
    container_name: authentication
    build:
      context: ./backend/authentication
      dockerfile: Dockerfile
    volumes:
      # - ./backend/authentication:/authentication
      - auth_data:/authentication
      # - ./backend/wait_for_db.sh:/wait_for_db.sh
    depends_on:
      - db_auth
    networks:
      - internal_network
      - auth
      - external
    env_file:
      - ./auth.env
    security_opt:
      - no-new-privileges:true

  db_auth:
    image: postgres
    container_name: db_auth
    volumes:
      - db_data_auth:/var/lib/postgresql/data
    networks:
      - auth
    env_file:
      - ./auth.env
    security_opt:
      - no-new-privileges:true

  core:
    container_name: core
    build:
      context: ./backend/core
      dockerfile: Dockerfile
    volumes:
      # - ./backend/core:/core
      - core_data:/core
      - media:/core/media
      # - ./backend/wait_for_db.sh:/wait_for_db.sh
    depends_on:
      - db_core
    networks:
      - internal_network
      - core
    env_file:
      - ./core.env
    security_opt:
      - no-new-privileges:true

  db_core:
    image: postgres
    container_name: db_core
    volumes:
      - db_data_core:/var/lib/postgresql/data
    networks:
      - core
      - internal_network
    env_file:
      - ./core.env

  game:
    container_name: game
    build:
      context: ./backend/game
      dockerfile: Dockerfile
    volumes:
      # - ./backend/game:/game
      - game_data:/game
      # - ./backend/wait_for_db.sh:/wait_for_db.sh
      - media:/game/media
    depends_on:
      - db_game
    networks:
      - internal_network
      - game
    env_file:
      - ./game.env
    security_opt:
      - no-new-privileges:true

  db_game:
    image: postgres
    container_name: db_game
    volumes:
      - db_data_game:/var/lib/postgresql/data
    networks:
      - game
    env_file:
      - ./core.env

networks:
  external:
    driver: bridge
  internal_network:
    internal: true
  auth:
    internal: true
  core:
    internal: true
  game:
    internal: true

volumes:
  db_data_auth:
  db_data_core:
  db_data_game:
  media:
  auth_data:
  core_data:
  game_data:
