# Generated by Django 5.1 on 2024-12-13 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_alter_match_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
