import { router } from "../main.js";

export default function TwoFA() {
  const html = `
  <section class="h-100 gradient-form" style="background-color: #222831;">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-xl-10">
          <div class="card rounded-3 text-black">
            <div class="row g-0">
              <div class="col-lg-6">
                <div class="card-body p-md-5 mx-md-4">

                  <form id="TwoFAForm">
                    <p>Insert the OTP generated by your authentication app</p>

                    <div data-mdb-input-init class="form-outline mb-4">
                      <input type="otp" id="otp" class="form-control"
                        placeholder="OTP" required />
                      <label class="form-label" for="otp">OTP</label>
                    </div>

                    <div id="errorMessage" class="alert alert-danger d-none" role="alert"></div>

                    <div class="text-center pt-1 mb-5 pb-1">
                      <button id="twoFAButton" data-mdb-button-init data-mdb-ripple-init class="btn btn-primary btn-block fa-lg gradient-custom-2 mb-3" type="button">Submit OTP</button>
                    </div>

                  </form>

                </div>
              </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  `;

  setTimeout(() => {
    const twoFAButton = document.getElementById('twoFAButton');
    const errorMessage = document.getElementById('errorMessage');

    // Add click event listener to the TwoFA button
    twoFAButton.addEventListener('click', async function (event) {
      event.preventDefault();

      // Hide any previous error message
      errorMessage.classList.add('d-none');
      errorMessage.textContent = '';

      // Get form values
      const username = localStorage.getItem("username")
      const otp = document.getElementById('otp').value;

      // Create the data object to send
      const TwoFAData = {
        username,
        otp
      };

      // Send the form data to the API using fetch
	  const response = await fetch('http://localhost:8002/api/auth/verify-otp/', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(TwoFAData),
      });

      // Handle the API response
      const result = await response.json();
      if (response.ok) {
        // alert('TwoFA successful!');
        // console.log('TwoFA result:', result);
        // Redirect to another page or handle success
        localStorage.removeItem("username")
        localStorage.setItem("access", result.access)
        localStorage.setItem("refresh", result.refresh)
        window.history.pushState({}, '', '/home');
        router();
      } else {
        // Display the error message
        errorMessage.textContent = result.error;
        errorMessage.classList.remove('d-none');
	  }
    });
  }, 0);

  return html;
}
