# Generated by Django 5.1 on 2024-09-18 20:41

import profile_data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=profile_data.models.avatar_file_path),
        ),
    ]
